### PR TITLE
feature/ATC-169

### PR DESCRIPTION
**Pull request by n8rzz**
completes #169 

Adds node server, .travis.yml and confirms integration with heroku

### CODE REVIEW

**Review by erikquinn — COMMENTED** [review]
Should I be concerned that [https://atc-dev.herokuapp.com/](https://atc-dev.herokuapp.com/) does not load? It just shows the page the way it looks when the bundle doesn't exist. I figure you may have just deployed again after this to test further improvements, but want to verify here.

**Comment by n8rzz** [comment]
yes, you should  I changed a setting and it apparently broke stuff.  I'll look at that tonight, too, and fix it.  should be a quick(ish) change if it is what I think it is.

**Comment by n8rzz** [comment]
heroku is fixed!

https://atc-dev.herokuapp.com/

**Comment by n8rzz** [comment]
@erikquinn  and, as you can see, travis passed it's checks

**Review by erikquinn — APPROVED** [review]

**Pull request merged**
