### PR TITLE
bugfix/ATC-1

### LINKED ISSUE #1: Aircraft data block colors are incorrect
currently on `develop`:
screen shot 2016-09-29 at 6 58 30 am

currently on `gh-pages`:
screen shot 2016-09-29 at 6 58 48 am

---

This should be located somewhere in the `CanvasController` and should just be a change in the `COLORS` constant that is being used for text and background.  If the color doesn't already exist, please add it to the `COLORS` constant.

### PR DESCRIPTION
**Pull request by n8rzz**
Fixes #1 and possibly #2.

Thats what I get for trying to be clever.  Some time ago I replaced `.clamp()` with the lodash version, `_clamp()` thinking that the two functions were the same.  They were not, this app's implementation of the `clamp()` function was slightly different.  And in such a way that moving over to the lodash `_clamp()` caused beaucoup minor bugs because the math was now wrong.

Changing back to a similar, though altogether different, version of `.clamp()` fixes the minor bugs.

### CODE REVIEW

**Review by erikquinn — CHANGES_REQUESTED** [review]
_Does_ seem to resolve #1 and #2. However, there is an ugly byproduct. I'm not sure if maybe it's [`CanvasController.js:905-906`](https://github.com/n8rzz/atc/pull/8/files#diff-1ce8a54e20349775a61dc7fdd9e23325R905) or what, but there is a massive decrease in apparent performance. It may not be a performance issue, perhaps just a reduction in the frequency with which the positions are redrawn in relation to the implementation of `clamp()` at those lines, or if it's actually slowing down enough to choke the thing up. A quick side-by-side shows a pretty significant difference.

Strange to see it doing this, haven't investigated very far yet, but something somewhere is slightly awry!

**Comment by erikquinn** [comment]
Correction: "Does seem to resolve #1, but not #2."
Also worth noting that the change in sluggishness is observable most easily under time acceleration, via `timewarp 50`.

**Comment by n8rzz** [comment]
Thats very curious.  Do you notice the same thing on `zlsa/gh-pages`?  This would be easy to test by pasting in the old `.clamp()` code inside my new implementation.  It seems odd that the old one would be faster, though, mine is a one liner.  But, I am making a few Math() calls so maybe that is the culprit?  I've seen stranger things happen.

Perhaps, at that warp speed, the circular dependency noted in #16 may _really_ be having an effect which is then slowing things down?  Thats a lot of stuff to update 60(ish) times a second.

**Comment by n8rzz** [comment]
wow, the results here are striking.  I ran a test on `TNCM` for 100 seconds with my new script and then with a _version_ of the old script and, well,  I'll let the screenshots do the talking:

**old script:**
screen shot 2016-10-06 at 7 22 02 am

screen shot 2016-10-06 at 7 22 55 am

**new script:**
screen shot 2016-10-06 at 7 37 43 am

screen shot 2016-10-06 at 7 37 54 am

There is obviously some variability in those results based on traffic and such.  But I would say that each test was similar enough for these results to be accurate.  Wow.

I've removed the Math work and reverted this back to ifs.  Please re-review when you can.

**Comment by erikquinn** [comment]
image

@n8rzz No change. But if I'm interpreting the above correctly, there's a crapload of idle time, which would indicate this isn't an issue of performance. Is that safe to say? I've only ever used the profiler to compare between things, and don't really know if the above assumption is a fair one.

If that _is_ the case, then perhaps it's the case that somehow the update rate was changed? eg `canvas_should_draw()` giving weird returns or something? It's got to be _something_ in this PR, because the develop branch has no such problem. :confused:

**Comment by n8rzz** [comment]
very interesting.  With what has changed, I wouldn't have expected that much of a performance hit.  Especially after the changes I made a few days ago.  The idle time is likely a result of the timeframe you are looking at.  You can adjust that by dragging the left or right side in either direction.



Stupid question: Did you re-build (`npm run build`) after you pulled?  I believe this branch has bundle in `.gitignore` cause its a pain to deal with those files in vc.

I'll bisect it and see if I can find a difference here.  This is a weird for sure.

**Comment by erikquinn** [comment]
Okay, sorry I was using the profile tab, but I can get that stuff from the timeline tab (which i've never used before, looks legit)...

## image

image

And yeah, it doesn't really make any sense why this is happening; from what I can tell, nothing has really changed that much that would do this sort of thing.

---

And I'm by no means an npm wizard lol all I've been doing is `npm install` whenever there's changes to `packages.json`, and running `gulp build` and `gulp watch` after each new checkout or update. Perhaps `npm run build` would call gulp to run the build task? (That would be neat, but news to me)

**Comment by n8rzz** [comment]
Yeah, timeline is good stuff.  That's where my screens from a few days back were taken from.

Right on, you're exactly correct.  The `npm run build` task is just a wrapper for a few tasks:
`"build": "gulp dist && npm run test"`.  I just wanted to make sure you are getting up-to-date code.  And if that is your process, you should be up to date.

See #32 for one issue I keep running into with the `watch` commands.  That is something to keep an eye on.  TL;DR a new build succeeds but the server continues to serve an old version long after a newer one exists.  It's a caching problem and its bullshit (excuse my french).  Tools are a pain in the ass sometimes, this really shouldn't even be a problem.  But, thats why I added the ticket.

**Comment by n8rzz** [comment]
@erikquinn I keep forgetting to ask, which editor do you use?  Do you have eslint installed?

**Comment by erikquinn** [comment]
@n8rzz Sublime Text 3 for the longest time, but this past week I've finally made the change to atom. I haven't installed eslint, no, I can get on that. I added something for generating the function description comments (dockblockr I think it was), and atom-editorconfig but that's it so far. If you have a list of goodies to add on to atom, definitely hit me with it!

**Comment by n8rzz** [comment]
This is the complete list of my plugins, via the package-sync plugin:

``` json
packages: [
  "autocomplete-js-import"
  "docblockr"
  "editorconfig"
  "emmet"
  "expose"
  "fast-eslint"
  "file-icons"
  "git-blame"
  "git-control"
  "git-time-machine"
  "highlight-selected"
  "hyperclick"
  "imdone-atom"
  "imdone-atom-github"
  "js-hyperclick"
  "json-converter"
  "language-babel"
  "language-elm"
  "language-fsharp"
  "language-rspec"
  "line-diff-details"
  "linter"
  "linter-elm-make"
  "linter-eslint"
  "linter-jsonlint"
  "linter-package-json-validator"
  "linter-rubocop"
  "linter-shellcheck"
  "linter-write-good"
  "merge-conflicts"
  "open-recent"
  "package-sync"
  "pigments"
  "pretty-json"
  "project-manager"
  "rails-rspec"
  "rails-snippets"
  "react"
  "rspec-snippets"
  "rubocop-auto-correct"
  "SS-Orca-Syntax"
  "ss-orca-ui"
  "tabs-to-spaces"
  "terminal-plus"
  "todo-show"
  "tree-view-copy-relative-path"
  "vim-mode"
]
```

the ss-orca-\* packages are my own (inconsistently titled it seems) syntax/ui themes.  I'm pretty picky about syntaxes and colors, and this is one of the reasons why I love Atom, I constantly make tweaks to how my syntax looks and feels.  Both of those packages are on my github if you're really curious.  I target mostly `{.bash, .js, .jsx, .rb,. yaml, .json}` file extensions for highlighting.

The other couple I will call out as absolute musts:
- hyperclick (cmd+click on an import and it takes you to the file)
- language-babel
- fast-eslint/linter-eslint
- package-sync (allows easier syncing of packages between computers)
- project-manager

**Comment by n8rzz** [comment]
@erikquinn  Are you still seeing any performance issues here?  I put this branch next to the current zlsa/atc and they looked very similar.  I didn't see anything that stood out as a drastic difference.  

Could you take a look at this one again when you have a few minutes?  Thanks!

**Comment by erikquinn** [comment]
@n8rzz Works fine now. I've found elsewhere that the jumpiness is a direct and reproducible result of lodash's `_clamp`. No idea why, but I'll explain in #15.

**Review by erikquinn — APPROVED** [review]

**Comment by n8rzz** [comment]
I would agree with that.  I like our current implementation here and I would bet that `_clamp()` is doing some numbering that is taking up more resources than what we're doing now.

I'll add an issue later to remove any that still remain and use our new one.

**Pull request merged**
