### PR TITLE
[WIP] feature/ATC-19

### PR DESCRIPTION
**Pull request by n8rzz**
There are several `v3.0.x` housekeeping changes in here that will get merged separately, but I wanted to throw this out there to start the discussion.

Major items of note here:
- The `.parse()` method of the `AirportModel`
- the `.getSID()` method of `AirportModel`
- All of the new files in the `/standardRoute` directory

Currently these new files are only implemented when calling `AirportModel.getSID()`, but my plan is to use these with `getSTAR()` also.  At least to start.  The work here is laying the groundwork for a more centralized place to find any information about fixes, waypoints, segments and routes.

Please, please, as questions!!

---

Synopsis, description, explanations and other thoughts:

This is a very top down structure where one thing creates the next. Its setup like this:

```
SidCollection -> [SidModel, SidModel, SidModel]
SidModel -> RouteSegmentCollection, RouteSegmentCollection, RouteSegmentCollection
RouteSegmentCollection -> [RouteModel, RouteModel, RouteModel]
RouteModel -> StandardRouteWaypointModel
```

lined up next to the json, you can see how the classes are split up:

``` javascript
// taken from klas.json
'sids': { // SidColelction
    'COWBY6': { // SidModel
        'icao': 'COWBY6',
        'name': 'Cowboy Six',
        'rwy': { // SidModel._runwayCollection {RouteSegmentCollection}
            '01L': ['_NAPSE068', 'NAPSE', ['RIOOS', 'A130+'], 'COMPS'], // RouteSegmentModel
            '01R': ['_NAPSE068', 'NAPSE', ['RIOOS', 'A130+'], 'COMPS'], // RouteSegmentModel
            '07L': ['WASTE', ['BAKRR', 'A70'], 'COMPS'], // RouteSegmentModel
            '07R': ['JESJI', ['BAKRR', 'A70'], 'COMPS'], // RouteSegmentModel
            '19L': ['FIXIX', ['ROPPR', 'A70'], ['CEASR', 'A80+'], ['HITME', 'A110+']], // RouteSegmentModel
            '19R': ['JAKER', ['ROPPR', 'A70'], ['CEASR', 'A80+'], ['HITME', 'A110+']], // RouteSegmentModel
            '25L': ['PIRMD', ['ROPPR', 'A70'], ['CEASR', 'A80+'], ['HITME', 'A110+']], // RouteSegmentModel
            '25R': ['RBELL', ['ROPPR', 'A70'], ['CEASR', 'A80+'], ['HITME', 'A110+']] // RouteSegmentModel
        },
        'body': ['COWBY'], // SidModel._bodySegment {RouteSegmentModel}
        'exitPoints': { // SidModel._exitCollection {RouteSegmentCollection}
            'DRK': ['NAVHO', 'DRK'], // RouteSegmentModel
            'GUP': [['MOSBI', 'A150+'], 'GUP'], // RouteSegmentModel
            'INW': [['CUTRO', 'A150+'], 'INW'] // RouteSegmentModel
        },
        'draw': [
            ['ROPPR', 'CEASR', 'HITME', 'COWBY', 'MOSBI', 'GUP*'],
            ['BAKRR', 'COMPS', 'COWBY', 'CUTRO', 'INW*'],
            ['_NAPSE068', 'NAPSE', 'RIOOS', 'COMPS'],
            ['COWBY', 'NAVHO', 'DRK*']
        ]
    },
    'SHEAD9': { // SidModel
        // ....
    }
}
```

This seems like a large amount of code to do what was done in 100 lines before, and it is a large amount of code to do that. That 100 lines did _only_ one thing, and it wasn't portable. Other parts of the application couldn't use that bit of logic. In fact, a few lines down in `.getSTAR()` this logic is nearly duplicated.

What this structure provides, is a neat little swiss army knife. With things set up like this we have a set of portable classes with a concise, single concern. These classes all work together to get
us the information we need.  They can also be extended to get us things we may need in the future.  These classes are tested, which is to say there are tests written for each class that can reliably tell when things break. These tests account for happy path interactions as well as some unhappy paths. Ive tried to be defensive with some of the important parts. You will see areas where I do something like

```
if (!(segment instanceof SegmentModel)) { ... }
```

Because we have these classes, we can now check the data as it flows into the application.
I don't want to try to add an object to the `RouteCollection` if it isn't a `RouteModel`, that will break things later and will lead to a bad time.

Admittedly, this is a very OOP approach. There may be other ways to this same type of thing but I feel that this is the cleanest one.  Especially for this application.

---

Please try not to pay too much attention to the naming. ~~There are a few files title `Sid*` these will likely change.  I worked out the logic while dealing with the `klas` sids, but everything here _should_ (dangerous programming word) work the same with STARS~~.  I haven't tried many other airports either, but I will be doing that soon.

I'm fairly confident it will work with everything. Even though it looks completely the actual logic behind all this code is exactly the same, it's just being accomplished in a completely different way.

### CODE REVIEW

**Comment by n8rzz** [comment]
@erikquinn here is what I was talking about yesterday.  Adding this here simply for visibility and discussion.  This branch is still a ways off.

**Comment by n8rzz** [comment]
I am especially proud of this little guy:

``` javascript
// StandardRouteModel.js

_generateFixList = (originSegment, bodySegment, destinationSegment) => {
    // in the event that one of these functions doesnt find a result set it will return an empty array.
    // we leverage then `lodash.compact()` below to remove any empty values from the array before
    // returning the `fixList`.
    // These functions are called synchronously and order of operation is very important here.
    const fixList = [
        ...originSegment,
        ...bodySegment,
        ...destinationSegment
    ];

    return _compact(fixList);
};

_findFixListForSidByRunwayAndExit = (runwayName, exitFixName) => this._generateFixList(
    this._findFixListForRunwayName(runwayName),
    this._findBodyFixList(),
    this._findFixListForExitFixName(exitFixName)
);

_findFixListForStarByEntryAndRunway = (entryFixName, runwayName) => this._generateFixList(
    this._findFixListForEntryFixName(entryFixName),
    this._findBodyFixList(),
    this._findFixListForRunwayName(runwayName)
);
```

**Comment by erikquinn** [comment]
```
SidCollection -> [SidModel, SidModel, SidModel]
StarCollection -> [StarModel, StarModel, StarModel]
TransitionCollection -> [TransitionModel, TransitionModel, TransitionModel]
AirwayCollection -> [AirwayModel, AirwayModel, AirwayModel]
IapCollection -> [IapModel, IapModel, IapModel]
```

@n8rzz Ref the top level of the hierarchy you showed, would it not be better to avoid the multiple implementations such as in the above? Just as you have abstracted all of this, I'd like all "instrument procedures" to be written exactly the same way, which would include (at least) SIDs, STARs, Transitions, Airways, and Instrument_Approach_Procedures. Would it not be better to have them all treated as a `Procedure`, and indicate which methods to use by a `Procedure.type` property?

```
ProcedureCollection -> [ProcedureModel, ProcedureModel, ProcedureModel]
ProcedureCollection -> [ProcedureModel, ProcedureModel, ProcedureModel]
ProcedureCollection -> [ProcedureModel, ProcedureModel, ProcedureModel]
ProcedureCollection -> [ProcedureModel, ProcedureModel, ProcedureModel]
ProcedureCollection -> [ProcedureModel, ProcedureModel, ProcedureModel]
```

As I'm writing this, it's actually seeming ickier, having them set up in classes would probably be better, so you can call the method on the SIDModel directly via dotting... Nonetheless, I'll continue with the post in case it gives you any ideas.

**Comment by n8rzz** [comment]
The thing to keep in mind here is not that we are dealing with a `SID` or a `STAR` but, really, we are dealing with a group of fixes organized in a particular way.  With very few exceptions, there isn't any difference between those procedures.  There are some, but thats one thing that generator function above addresses.

Now this is currently implemented only for SIDs and STARs.  But the principles should be very similar.  Off the top of your head, are there any airports I should look at for those other procedures?  I could look through the files, but you may know one of the top of you head :-)

I'm very excited to discuss this more!

**Comment by n8rzz** [comment]
...and after re-reading your comments, yes, it _would_ be better to move away from the specificity of `SidCollection`, etc.  I didn't update my diagram after I made the changes.  SidCollection is now named `StandardRouteCollection` and `StandardRouteModel`.

As far as differentiating between the various types (SID, STAR, etc) that is done in the `AirportModel` by using and appropriate property name.  ex: 

``` javascript
this.sidCollection = new StandardRouteCollection(sidList);
this.starCollection = new StandardRouteCollection(starList);
```

These classes are also easy to extend for things that haven't been addressed already for those other procedure types.

**Comment by n8rzz** [comment]
seems I was _way_ too defensive in the constructors of some of these classes.  Instantiation fails on several airports.  Easy fix and now I have new test cases to add.

If you're giving this branch the run around, stick with `klas` for now.

**Comment by erikquinn** [comment]
@n8rzz Just to verify here: reference the `WIP` label, this is still in progress, and you aren't waiting for me to review, correct?

**Comment by n8rzz** [comment]
That is correct. I just put that here for visibility and discussion. Feel free to ask questions and raise concerns. 

I should actually close this one and open one for ATC-18, which continues on this work.

**Comment by n8rzz** [comment]
That is correct. I just put that here for visibility and discussion. Feel free to ask questions and raise concerns. 

I should actually close this one and open one for ATC-18, which continues on this work.

**Comment by n8rzz** [comment]
closed in favor of #35. we will continue discussion on that PR.

**Pull request closed without merging**
