### PR TITLE
feature/ATC-88

### PR DESCRIPTION
**Pull request by n8rzz**
completes #88 

Moves list of airports to load out of bundle allowing for additions and removals without the need to re-build the app.

### CODE REVIEW

**Review by erikquinn — COMMENTED** [review]
image

Not sure if I'm doing something wrong, but I removed `ksea.json` from `assets/airports`, and from the load list, retranspiled. It is gone from the in-game list (good). Then I added the file back in and put it back in the load list, did a simple page refresh, it is back in the in-game list (good). But then when I try to load it, it just spins, and eventually konks out here:

image

**Comment by n8rzz** [comment]
Yeah, that's that other PR I have that I think you just approved. That will fix this error.

**Comment by erikquinn** [comment]
Gotcha. The changes all _look_ to make sense, so I'll approve it as is then.

**Review by erikquinn — APPROVED** [review]

**Comment by n8rzz** [comment]
@erikquinn just merged in the PR that fixes the `areas` error you were seeing here.  I know you already approved this, but when you have a minute, could you test this locally?  I want to be extra sure that this works before I merge.

**Comment by erikquinn** [comment]
> @erikquinn just merged in the PR that fixes the areas error you were seeing here. I know you already approved this, but when you have a minute, could you test this locally? I want to be extra sure that this works before I merge.

Like a charm this time. :+1:

**Comment by n8rzz** [comment]
:shipit:

**Pull request merged**
