### PR TITLE
feature/ATC-186

### PR DESCRIPTION
**Pull request by Dabea**
Changed function names in the FixCollection from init() and destroy() to addItems() and removeItems()
this is for issue #186

### CODE REVIEW

**Review by n8rzz — CHANGES_REQUESTED** [review]
Looks good Abe!

Two things to call out that I didn't tell you about before hand:  Be sure to title your PR with just the branch name and reference the issue the this PR addresses in the description (which you did).  The other thing, which I also didn't mention, be sure to add this issue to the changelog file.  This would fall under the Minor issues heading.  I usually just copy and paste my PR description to the changelog.  Take a look at the other entries in there and follow that same format.

Other than the administrative stuff you didn't know about, good work! 👍

**Comment by Dabea** [comment]
I wondered about the change log after i updated it and was going to ask how that was updated. However I did also wonder why this was marked with #190 and not #186? was it something I did incorrectly?

**Comment by n8rzz** [comment]
nope, you're good.  The #190 is a **Pull Request** number whereas the #186 is an **Issue Number**.  They are both available for linking within github but issues and PRs are assigned numbers independently of each other.

**Comment by Dabea** [comment]
I have updated the change log with the changes from issue #186

**Review by n8rzz — APPROVED** [review]

**Pull request merged**
